### ISSUE TITLE
Rozwój forka?

### ISSUE THREAD

**Issue by NotJustPizza** [Wruczek/FunnyGuilds-Reloaded#1]
Macie zamiar rozwijać ten fork, czy już jest martwy?

**Comment by Wruczek** [comment]
Fork będzie rozwijany, nie martw się ;)
Dziś wieczorem spróbuje rozpocząć aktualizacje wtyczki pod 1.8, potem przyda się nowa baza danych

**Comment by NotJustPizza** [comment]
Ja dziś mam chwilę to mogę pomóc przy bazie danych. Tylko powiedz co ma w niej być. Oczywiście nadal pozostaje przy proponowanej bazie: https://gist.github.com/SlimaKCoder/746e89ebdf2b3b9f3e21, ale wszelkie zmiany są mile widziane.

**Comment by TheMolkaPL** [comment]
Ja użyłbym właśnie Twojej propozycji.

**Comment by Wruczek** [comment]
Też jestem za (jeśli tylko wszystko się zgadza)

**Comment by kamcio96** [comment]
Tylko się zdecydujecie :P albo _ albo kolejna litera duża. Chodzi mi o nazwy kolumn :)

**Comment by TheMolkaPL** [comment]
Ja mogę ogarnąć obsługę bazy w pluginie.

Mam tylko, taką uwagę do @SlimaKCoder twojej bazy taką, aby zamiast `mojaZmienna` używać `moja_zmienna`, tak jak to jest w ID. `isValidated` -> `validated`

**Comment by kamcio96** [comment]
I jeszcze, w tabeli np users nie powinno być user_id a samo id

**Comment by TheMolkaPL** [comment]
No to chyba do zamknięcia. Fork jest rozwijany. Piszcie w #2
