### ISSUE TITLE
Po co wam ten cały Security przed FreeCamem?

### ISSUE THREAD

**Issue by SocketByte** [Wruczek/FunnyGuilds-Reloaded#10]
Skoro nie można ingerować w server-side za pomocą FreeCama, to po co to?
https://github.com/Wruczek/FunnyGuilds-Reloaded/blob/master/src/main/java/net/dzikoysk/funnyguilds/system/security/SecuritySystem.java

**Comment by Wruczek** [comment]
Takie klienty jak Huzuni wysyłają pakiety o integracji z np. kryształem, FG to odbiera i niszczy gildię.
Sam miałem z tym duży problem na moim serwerze, ludzie niszczyli gildię z odległości np. 300 bloków, wiem z logów.

**Comment by SocketByte** [comment]
A to nawet nie wiedziałem że cokolwiek ingeruje, myślałem że działa to jedynie po stronie klienta, i nijak wpływa na serwer.

**Comment by kamcio96** [comment]
Przejmowanie gildi lepiej zrobić na evencie, wtedy minecraft sprawdza odległość :)

**Comment by NotJustPizza** [comment]
@kamcio96 
To do dzieła, poprawiaj jak powinno być!

**Comment by kamcio96** [comment]
uwierz mi, nam zdecydowanie ważniejsze rzeczy do roboty, i ja juz mówiłem, nie będę poprawiać tutaj nic ;)

**Comment by NotJustPizza** [comment]
@kamcio96 
No widzisz... zrobiłbyś coś dla ludzi, a nie grał w CSa :P

**Comment by kamcio96** [comment]
Ty też mógłbyś zrobić coś dla ludzi i przestać pisać głupie komentarze które i tak nic nie wnoszą do życia ;) gadałem z molkiem, on wie dlaczego nie chce się angażować w ten projekt :)

**Comment by NotJustPizza** [comment]
@kamcio96 
Nawet jeśli moje komentarze uznajesz za głupie to po trochu robię swoje. I zawsze lepiej tyle niż nic :P 

P.S. A to komu się zwierzasz to już Twoja sprawa :P

**Comment by kamcio96** [comment]
może nie głupie, ale trochę bez sensu
i ja też robie swoje ;)

**Comment by Wruczek** [comment]
Security system zostawiamy, jest potrzebny.
Zamykam.

**Comment by kamcio96** [comment]
@Wruczek weź lepiej się zajmij pisaniem, a nie ogarnianiem issue ;)
