### ISSUE TITLE
Nie dzialajaca komenda.

### ISSUE THREAD

**Issue by opentanystiv** [Wruczek/FunnyGuilds-Reloaded#16]
Witam, posiadam plugin funnyguilds 4.1.1 tribute.
Gdy wpisuje na serwerze /g pisze Ta komenda jest wylaczona.

**Comment by kamcio96** [comment]
https://github.com/FunnyGuilds/FunnyGuilds
Polecam też przeczytać `config.yml` przed uruchomieniem 😒
