### ISSUE TITLE
Ogólna dyskusja na temat wtyczki

### ISSUE THREAD

**Issue by Wruczek** [Wruczek/FunnyGuilds-Reloaded#2]
# Spis treści i notatki
## Plugin

@TheMolkaPL @Wruczek 
- [Panda](https://github.com/Panda-Programming-Language/Panda) - jakieś tam pandowe skrypty Dzikiego _(dependency)_
- [BasicDataSource](http://commons.apache.org/proper/commons-dbcp/api-1.2.2/org/apache/commons/dbcp/BasicDataSource.html) - connection pool od Apache _(dependency)_
## Po napisaniu bazy danych

@TheMolkaPL @Wruczek
- Zająć się: #348, #341, #288, #336 oraz #299 (pisałem o tym w #325), #328
- Przepisać scoreboardy na pakiety
## Ranking w PHP

@SlimaKCoder: [projectQ-Reloaded](https://github.com/SlimaKCoder/projectQ-Reloaded)
- [FluentPDO](http://lichtner.github.io/fluentpdo/) _(dependency)_
- [Twig](https://github.com/twigphp/Twig) _(dependency)_
- _jak wybiorę resztę libów to dodam i muszę je jeszcze sprawdzić podczas pisania_
## Baza danych MySQL

@SlimaKCoder 
- [Struktura bazy danych SQL](https://gist.github.com/SlimaKCoder/746e89ebdf2b3b9f3e21) - planowany wygląd bazy

**Comment by TheMolkaPL** [comment]
Nie wydaje mi się.

**Comment by Wruczek** [comment]
Dobra, jeśli @Dzikoysk nie pomoże to napiszę coś własnego

**Comment by kamcio96** [comment]
https://github.com/Panda-Programming-Language/Panda?

**Comment by Wruczek** [comment]
To mam, chodzi o wersję klasy Panda przystosowanej pod FunnyGuilds.
Ale już sobie poradziłem.

**Comment by kamcio96** [comment]
@Wruczek dodaj mnie, bo nie chce mi się forka robić xD

**Comment by Wruczek** [comment]
Dodany

**Comment by NotJustPizza** [comment]
@TheMolkaPL 
Ja ogólnie trzymałem się zasady, że nazwy tabel oraz id są z "_", a reszta z dużą literą, ale mogę to wszystko uściślić do "_".

@kamcio96 
Lepiej by było zostawić jak jest, czyli "user_id", "guild_id", etc, bo to klucze podstawowe, ale również obce. Lepiej by w zapytaniach nie pojawiło się dwa razy "id".

**Comment by NotJustPizza** [comment]
@Wruczek @TheMolkaPL @kamcio96 
https://gist.github.com/SlimaKCoder/746e89ebdf2b3b9f3e21

**Comment by dzikoysk** [comment]
Masz na myśli jakiekolwiek użycie Pandy w fg? Jeżeli tak, to na razie ogarniała wszystko odnośnie plików - zamiast yaml'a. Można też później dodać api fg, co pozwoli tworzyć w sumie fajne i wydajne skrypty

**Comment by kamcio96** [comment]
@SlimaKCoder ale w tabeli users nie powinno byc user_id, bo sugeruje to że jest to z innej tabeli
np:
log_id [int, not null, autoincrement,  primary key],
killer_id [int, not null, foreign key],
victim_id [int, not null, foreign key]
log_id ewidentnie powinien mieć nazwę id, bo jest kluczem głównym. I wtedy od razu widać co jest najważniejsze.

**Comment by SlimaKCoder** [comment]
@kamcio96
"log_id" jest pierwszą kolumną, do tego ma ustawianą flagę "PRIMARY KEY" - to w zupełności wystarczy, żeby nie pomylić jej z kluczem obcym. Zamiana nazwy na "id" może i nie ma wielkiego znaczenia, ale używając konwencji, która jest zawsze wiemy o czego "id" chodzi.

**Comment by kamcio96** [comment]
No dobra, w sumie to jebie mnie to, ale mówię tylko jak powinno być ;)

**Comment by NotJustPizza** [comment]
@kamcio96 

W sumie jest dobrze jak jest, część "id" jest jednocześnie kluczami podstawowymi i obcymi lub fragmentem klucza.... przynajmniej zawsze wiadomo, o czego "id" chodzi :)

**Comment by kamcio96** [comment]
Po tabeli wiadomo o co chodzi, a wprowadzanie nazwy tylko miesza, nie wiadomo później który jest ten najważniejszy. Tak to trzeba będzie się zastanawiać "aaa, ta tabela, to tutaj jest podstawowym to" Jak dla mnie mylący zapis.

**Comment by NotJustPizza** [comment]
@kamcio96 

Zależy od konwencji jakiej się trzymasz. Dla świętego spokoju zmieniłem to, a i poprawiłem kilka przeoczeń: https://gist.github.com/SlimaKCoder/746e89ebdf2b3b9f3e21/revisions

**Comment by kamcio96** [comment]
Dobra, trochę pozmieniałem, jakby ktoś mógł przetestować (uruchomić i zobaczyć co nie działa) to byłbym wdzięczny [link](http://kamcio96.pl/FunnyGuilds-Reloaded.jar) :smile:

Teraz wasza kolej :smile:

**Comment by TheMolkaPL** [comment]
`artifactId` nie powinien być w całości małymi literami? `funnyguilds-reloaded`

**Comment by dzikoysk** [comment]
Miało być PandaGuilds, a nie Reloaded!

**Comment by kamcio96** [comment]
@TheMolkaPL szczerze to nie wiem, nigdzie nie widziałem że musi być małymi literami, a teraz jakoś lepiej wygląda :smile:

**Comment by TheMolkaPL** [comment]
@kamcio96

> **artifactId** is the name of the jar without version. If you created it then you can choose whatever name you want with lowercase letters and no strange symbols. If it's a third party jar you have to take the name of the jar as it's distributed.
> 
> eg. `maven`, `commons-math`

https://maven.apache.org/guides/mini/guide-naming-conventions.html

@Dzikoysk wcale nie, miało być PendolinoGuilds!!

**Comment by kamcio96** [comment]
Oki, to zmień ;) 

I weź coś jeszcze pozmieniaj, a nie tylko błędy widzisz xD

**Comment by TheMolkaPL** [comment]
Jestem na telefonie do wieczora xd

**Comment by kamcio96** [comment]
Dobra dobra, winni się tłumaczą xD

**Comment by NotJustPizza** [comment]
Niech zostanie nazwa jak jest... bo do porozumienia nie dojdziemy, więc nie ma co zmieniać.

**Comment by NotJustPizza** [comment]
@Wruczek 

Jestem tu jedynym nie-collaborator'em? xD

**Comment by kamcio96** [comment]
@SlimaKCoder a coś pisać będziesz? xD Jak tak to rób PR :stuck_out_tongue_closed_eyes:

**Comment by kamcio96** [comment]
:P

**Comment by NotJustPizza** [comment]
@kamcio96 Z SQL będę pomagać ;)

Przepisuje obecnie projekt z pesudokodu na język SQL: https://gist.github.com/SlimaKCoder/746e89ebdf2b3b9f3e21

**Comment by TheMolkaPL** [comment]
Wrócę do domu wieczorem to się wezmę za obsługę bazy danych.

Jeszcze trzeba rozwiązać nieszczęsne pliki. Nie każdy współczesny technik serwera Minecraft potrafi podłączyć plugin pod bazę danych. (:cry: & :laughing:)

Proponuje SQLite.

**Comment by NotJustPizza** [comment]
SQLite i MySQL (oparte na języku SQL) mają praktycznie taką samą składnie, dlatego plugin powinien móc używać obu.

**Comment by kamcio96** [comment]
@SlimaKCoder wiemy, my to naprawdę wiemy xD I na tym gist na dole wklej czysty opis tabel też

**Comment by TheMolkaPL** [comment]
Najszybciej i najwygodniej się to robi. Niestety jest to bardzo wolne, a ktoś, kto chciałby edytować własnoręcznie dane w bazie to potrzebuje do tego specjalnego oprogramowania.

Co do killi/deadów w tabeli w bazie, to dodałbym kolumnę, gdzie można by wpisać ID wojny, w której się to toczyło. Umożliwi to wyświetlanie dokładniejszych informacje na stronie WWW.

**Comment by TheMolkaPL** [comment]
Co do killi/deadów w tabeli, to dodałbym kolumnę, gdzie można by wpisać ID wojny, w której się to toczyło. Umożliwi to wyświetlanie dokładniejszych informacje na stronie WWW.

**Comment by NotJustPizza** [comment]
@TheMolkaPL 

Dlatego albo idziesz na łatwizne i SQLite bez większego namysłu, albo wybierasz porządnego MySQL, ale musisz go sobie skonfigurować.

**Comment by kamcio96** [comment]
Myślę że nie będzie problemu z zapisywaniem tego, interfejs + 3 rożne implementacje ( + pliki jeszcze). 
@TheMolkaPL masz jakąś fajną klase do MySQL i SQLite czy chcesz coś mojego?

**Comment by TheMolkaPL** [comment]
- Ja oparłbym to na jednej klasie abstrakcyjnej, gdzie byłaby metoda do wysyłania zapytania i ewentualnego zwrotu `ResultSet`.
- Do tego implementacje tej klasy dla MySQL i SQLite.
- Oddzielny wątek, gdzie dodawałoby się statycznie zapytania do kolejki, oraz ich wykonywanie właśnie w tym wątku.
- Klasy, gdzie każda odpowiada za jedno zapytanie (jednej kategorii, gdzie w konstruktorze podaje się dokładne parametry). Dzięki temu zapytania SQL nie będą rozsypane po całym pluginie, tylko w jednych podanych dla nich klasach. Pobieranie danych to po prostu tworzenie takiego obiektu takiego zapytania i dodanie do kolejki do wątku bazy danych.

Tak to widzę :3

**Comment by NotJustPizza** [comment]
Przepisałem już całość na język SQL i dodałem "conquest_id" do zabójstw. Przy dodawaniu bezpośrednio do MySQL nie ma już żadnych błędów. Mam nadzieję, że po zmianie bazy danych nie będzie takich masakrycznych zapytań jak kiedyś: https://github.com/SlimaKCoder/projectQ/blob/Stable/class/FunnyGuildsQueries.class.php

**Comment by TheMolkaPL** [comment]
No to został tylko connection pool. Ja wybrałbym [BasicDataSource](http://commons.apache.org/proper/commons-dbcp/api-1.2.2/org/apache/commons/dbcp/BasicDataSource.html) z Apache Commons.

Co do zabezpieczenia przed SQL Injection to będę używać [PreparedStatement](http://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html).

**Comment by kamcio96** [comment]
@TheMolkaPL kiedy wrzucisz to? chciałbym Ci coś pokazać, ale nie wiem jak to wytłumaczyć xD

**Comment by TheMolkaPL** [comment]
@kamcio96 5d23c4c5d40ca6d67dab82a90b637b3da496f93c i c71417845bedcc072271e5ce030a89434cd5901c
Co o tym sądzicie?

**Comment by kamcio96** [comment]
Czego innego się spodziewałem, zaraz pokaże Ci moją propozycje ;)

**Comment by dzikoysk** [comment]
Zaktualizujcie sobie pandę, bo się trochę zmieniło. Później będzie boleć :panda_face:

**Comment by kamcio96** [comment]
@TheMolkaPL zobacz na mój system, ideą jest jak na razie jedna zmienna w klasie Rank (kills)
np. po wykonaniu kills.add(1) automatycznie by się aktualizowało w bazie danych (lub w pliku, zależy od implementacji Database i DataSource)
Nie do końca ogarniam system Basic i BasicType (jak dla mnie to lepiej byłoby to oprzeć na interfejsach), więc możliwe że coś zjebałem, klasę Rank podzieliłbym na 2 osobne, łatwiej by się operowało na tym systemie danych.

**Comment by SlimaKCoder** [comment]
@kamcio96 
Baza aktualizuje się, gdy gracz:
- zabija gracza,
- loguje się,
- przy zwiększaniu się progresu wojny (wyliczało by w oparciu zabicia, zgony i czas),
- używa komend

**Comment by kamcio96** [comment]
@SlimaKCoder ja wiem że Ty się starasz, bardzo to doceniam. Ale czasami powstrzymaj się od komentarzy :smiley: idę po :beer:

**Comment by dzikoysk** [comment]
@kamcio96 jest maven, dodałem teraz jeszcze target do pom'a. Build'a chyba nie dodaję, bo niczego panda nie wymaga, a i każdy sobie to dowolnie ogarnie

**Comment by kamcio96** [comment]
@Dzikoysk 
Fakt, nie zauważyłem xD
I już miałem pisać o to 1.7 :D 
Dodaj jeszcze:

```
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```

**Comment by dzikoysk** [comment]
O, rzeczywiście nie ma kodowania, musiałem zgubić :<!

**Comment by kamcio96** [comment]
I coś nadal nie chce się skompilować :/
Btw w package może być _ ? Tzn być może, ale czy powinno?

**Comment by dzikoysk** [comment]
Czo Ci się nie kompiluje - sama panda, czy panda z fg?

**Comment by kamcio96** [comment]
Sama panda http://scr.hu/1s1h/zx90m

**Comment by dzikoysk** [comment]
Ohhh... moja wina. Coś mi importy podmieniło w niektórych klasach, mehhh

**Comment by kamcio96** [comment]
I usuń _ Jakoś dziwnie wygląda xD
Możesz dać package tylko panda.lang :D tak jak java.lang

**Comment by dzikoysk** [comment]
Teraz na szybko coś poprawiłem, resztę skończę jutro. A nazwa jest poprawna i wygląda dobrze :panda_face:

**Comment by kamcio96** [comment]
Dobra, to ja forka usuwam xD

**Comment by dzikoysk** [comment]
Tzn ten, już działa, tylko nie ma builda w pomie. Dodam w takim razie jutro, bo przy testach w sumie może się przydać

**Comment by TheMolkaPL** [comment]
Baza fajna, tylko nie zbyt ochrania przed SQL Injection. Nie używaj lombok, bo nigdzie w projekcie nie był używany. To też tyczy się code style.

**Comment by kamcio96** [comment]
Wszystko pisałem na szybko, tylko żeby był commit. 
Co do ochrona przed sql injection to trzeba by jakiegoś replace tam zrobić. 

I czemu nie lombok? :( jest bardzo fajny

**Comment by TheMolkaPL** [comment]
Jak pisałem; nigdzie w projekcie nie był używany, więc nie rozumiem dlaczego teraz miałby być używany.

**Comment by kamcio96** [comment]
no dobra, to trzeba będzie ręcznie robić te konstruktory xD

**Comment by TheMolkaPL** [comment]
I trzymaj się code style. Ja muszę poprawić dodatkowy enter na końcu klas. Jeżeli chodzi o bazę, to będzie jedna klasa, gdzie będą wszystkie metody do tworzenia `DataSource`?

**Comment by kamcio96** [comment]
Będą 3 klasy które implementuja DataSource (zmieniłbym nazwę) + 3 klasy które implementuja Database

**Comment by TheMolkaPL** [comment]
W sumie nie wiem które rozwiązanie byłoby lepsze. Twoje wymaga masy metod w `Database`, a mój działa oddzielnie niż dane w zmiennych. Chociaż mój w ogóle nie trzyma żadnych danych, tylko polega na wysyłaniu zapytań do bazy.

**Comment by kamcio96** [comment]
Można połączyć oba :smile: 

Do WriteQuery dodaj Callback, przy tworzeniu statement sprawdzaj czy jest != null
I po wykonaniu query statement.getGeneratedKeys() i do callbacka :smiley:

**Comment by TheMolkaPL** [comment]
Ale po co Ci pobieranie danych z zapisu? xd

**Comment by kamcio96** [comment]
dodajesz gildie i pobierasz id rekordu, żeby później lepiej identyfikować :)

**Comment by TheMolkaPL** [comment]
No to można dodać ;)
Będę wieczorem w domu to ogarnę.

**Comment by kamcio96** [comment]
nie nie nie, teraz ja to co innego pisze xD
Btw. w tym pluginie bedzie dużo zmian :/

**Comment by TheMolkaPL** [comment]
Co o tym myślisz @Wruczek?

**Comment by kamcio96** [comment]
No właśnie, czekamy na twoje commity :smile:

**Comment by dzikoysk** [comment]
Panda się już pięknie kompiluje

**Comment by Wruczek** [comment]
@kamcio96 Co sądzisz o przeniesieniu FunnyLog do util?

Co do mnie, wieczorkiem spróbuje pobawić się z issues z oficjalnego projektu i dodać takie małe poprawki jak komendy admina w konsoli itp. Mam w planach dodanie ilości punktów jako suffix nad głowami graczy. Co o tym sądzicie?

**Comment by kamcio96** [comment]
wstrzymaj się z tym chwile, system scoreboard jest do przepisania, jak dla mnie dużo rzeczy jest do przepisania, chyba łatwiej byłoby zrobić nowy plugin xD

**Comment by NotJustPizza** [comment]
Panowie, zacznijcie od bazy. Jak już baza będzie to każdy może zając się czym innym. Ale grunt to solidne podstawy, bez tego nie ruszymy i zrobi się bajzel!

**Comment by TheMolkaPL** [comment]
@SlimaKCoder tylko nie jest rozstrzygnięte, która baza danych będzie używana. Moja czy @kamcio96. Różnica jest taka, że baza Kamcia to także zmienne w pluginie. U mnie jest to tylko wysyłanie poleceń o aktualizacji/pobraniu danych.

**Comment by kamcio96** [comment]
@TheMolkaPL 
Teoretycznie można to jakoś połączyć. Tylko że przydałoby się pozbyć tego `instanceof` który sprawdza jakie to query :D
Moje zmienne mają taką zaletę, że pisząc dalszą część pluginu jest łatwiej i szybciej. Do tego nie ma znaczenia jaki system zapisu jest wykorzystany.

**Comment by Wruczek** [comment]
@kamcio96 Dobra, wstrzymam się z scoreboardem.

@All
Po bazie danych proponuję przepisanie tych wszystkich nametagów na pakiety.

> @Wruczek
> Jestem tu jedynym nie-collaborator'em? xD

Jeśli chcesz, mogę Cię dodać, nie ma problemu :P

**Comment by NotJustPizza** [comment]
Mógłbyś, jak ogarnę ze swoim kodem PHP5 to mogę się udzielać również przy Java :P

**Comment by Wruczek** [comment]
@SlimaKCoder Dodałem.

**Comment by NotJustPizza** [comment]
Ja do PHP5 chyba użyję tego: http://lichtner.github.io/fluentpdo/ Miałem używać jakiegoś całościowego frameworka, ale widzę, że połowy funkcji z nich nie potrzebuje, a do tego wymagają composera, a niestety z nim sobie typowy admin MC za Chiny nie poradzi :P

**Comment by kamcio96** [comment]
@TheMolkaPL BasicDataSource automatycznie wznawia połączenie?

**Comment by NotJustPizza** [comment]
Pytanie: Każdy region w bazie będzie miał inną nazwę? Będziecie robić jakieś komendy typy "`/fg regioninfo <nazwa_regionu>`"?

**Comment by kamcio96** [comment]
a nie gildia = region?

**Comment by NotJustPizza** [comment]
@kamcio96 @TheMolkaPL @Wruczek
No właśnie ma być możliwość kilku regionów, tak przyszłościowo. To w takim razie każdy region ma mieć inną nazwę dla komend, czy może potraktować tą nazwę jako opis, jak przy homach?

**Comment by TheMolkaPL** [comment]
@SlimaKCoder raczej jako opis
@kamcio96 chyba tak

**Comment by NotJustPizza** [comment]
@TheMolkaPL 
Ok tak zrobię.

Lukajcie co jakiś czas na zmiany: https://gist.github.com/SlimaKCoder/746e89ebdf2b3b9f3e21

**Comment by kamcio96** [comment]
Dobra, to w takim razie kontynuacja tego pluginu nie ma sensu, i tak trzeba będzie wszystko zmienić. Więcej roboty niż pożytku :disappointed: 
Ja odpadam, ale powodzenia :wink:

**Comment by dzikoysk** [comment]
Mówicie cały czas o zapisie, a w tym forku nie ma żadnego, więc nie ma co zmieniać. Dlatego nie ogarniam o czo Ci chodzi xD

**Comment by NotJustPizza** [comment]
@kamcio96 
Wut, dlaczego tak z dupy? Po za tym to tylko zostawienie sobie opcji na przyszłość, jak na razie każda gildia ma jeden teren ;)

**Comment by kamcio96** [comment]
@all jak chcecie pogadać to ts: ts.kamcio96.pl
Troche nie chce mi się pisać, i mam inne rzeczy do pisania :blush:

**Comment by dzikoysk** [comment]
#lokowanieProduktu

**Comment by NotJustPizza** [comment]
@Dzikoysk 

To samo pomyślałem :P

**Comment by NotJustPizza** [comment]
Tworzę sobie testową bazę danych, muszę mieć na czym pracować...

![Screen](http://s12.postimg.org/5javtiw1p/Zrzut_ekranu_z_2015_10_15_22_07_49.png)

**Comment by kamcio96** [comment]
Ip zmienione, czepiacie się xD

**Comment by NotJustPizza** [comment]
@all 
Co chcielibyście by było na stronie WWW? Tylko statystyki? Może jakiś admin panel na hasło również?

**Comment by TheMolkaPL** [comment]
Co miałoby się w nim znajdować?

**Comment by Wruczek** [comment]
@SlimaKCoder Ja mogę pomóc ze stroną www, mam kod ze strony starego serwera na dysku.

Stary ss:
![](https://scontent-waw1-1.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/1503269_1545376169046741_7805011339417406719_n.png?oh=465a13ca09dcc36d3dcfebf9bfaf0976&oe=56D002AC)

**Comment by NotJustPizza** [comment]
@TheMolkaPL 
- możliwość usuwania danych z bazy (graczy, zabić, gildii), czyli czyszczenie,
- możliwość blokowania gildii,
- możliwość rozpoczynania i zakańczania wojen,
- możliwość zmiany relacji gildii,
- możliwość ustawienia punktów graczowi,
- możliwość powiększania regionów gildii (można by nawet za SMS :P),
- możliwość zmiany pozycji home,
  i co tam sobie jeszcze wymyślę :package: 

Do tego podstawowa konfiguracja była by zarządzana z panelu admina.

**Comment by NotJustPizza** [comment]
@Wruczek 
A to pisane obiektowo jest? Jeżeli funkcyjne to już lepiej mi się oprzeć na: https://github.com/SlimaKCoder/projectQ

**Comment by Wruczek** [comment]
@SlimaKCoder Kod PHP to crap, pisałem to jak się nie znałem na PHP. Ale chodzi mi o użycie tego jako template. Cały kod PHP by się przepisało

**Comment by TheMolkaPL** [comment]
@SlimaKCoder brzmi fajnie. Chociaż co do powiększania cuboidów za SMS to pay2win = :hankey: & niezgodne z EULĄ.

**Comment by NotJustPizza** [comment]
@Wruczek 

Taki sobie, po za tym na boostrapie?

@TheMolkaPL 

Racja, to bez SMSów :P

**Comment by Wruczek** [comment]
@SlimaKCoder Na bootswatchu, tak jak Twoje ;)

**Comment by NotJustPizza** [comment]
@Wruczek 

Zmieniam trochę koncepcję, więc nie będę używać bootswatcha ;P

**Comment by Wruczek** [comment]
@SlimaKCoder Czy to będzie coś w standardowym stylu jak np. [XCrafters](http://web.archive.org/web/20141218153203/http://xcrafters.pl/)? Proste, łatwe w użyciu i ładnie wygląda. Chodzi mi głównie o rozmieszczenie elementów na stronie.

**Comment by TheMolkaPL** [comment]
@Wruczek mi się takie _(nie)_rankingi nie podobają. Dla mnie ranking to ranking, czyli pełne możliwości sortowania, itd. Klikasz na kills to sortuje po ilości killi, jeszcze raz - od najgorszych, itd.

**Comment by Wruczek** [comment]
@TheMolkaPL Zawsze można użyć [DataTables](https://datatables.net/extensions/responsive/examples/styling/bootstrap.html) zamist zwykłych tabel i zrobić ładowanie przez Ajax

**Comment by NotJustPizza** [comment]
@TheMolkaPL @Wruczek 
Raczej zrobię statyczne tabele, ale na pewno inaczej niż u XCrafters.

**Comment by TheMolkaPL** [comment]
9accc36e4d71fdd4bc1123e7a91193a5f5cf4acf

**Comment by NotJustPizza** [comment]
@TheMolkaPL 
Dodaj tam do tabel zmienną z domyślnym prefixem "funnyguilds_".

**Comment by TheMolkaPL** [comment]
@SlimaKCoder To trzeba dodać do konfiguracji w `config.yml`. Domyślną wartością będzie `funnyguilds_` https://github.com/Wruczek/FunnyGuilds-Reloaded/commit/9accc36e4d71fdd4bc1123e7a91193a5f5cf4acf#diff-f7f8f3333775c4fe9d322e47057830c1R83

**Comment by NotJustPizza** [comment]
@TheMolkaPL 
Dokładnie. Trzeba to dodać do konfiguracji, ale i od razu do nazw tabel trza przykleić zmienną z tymże prefixem ;)

**Comment by TheMolkaPL** [comment]
No to dałem linka - https://github.com/Wruczek/FunnyGuilds-Reloaded/commit/9accc36e4d71fdd4bc1123e7a91193a5f5cf4acf#diff-f7f8f3333775c4fe9d322e47057830c1R83.
Przy pobieraniu nazwy tabeli doklejam mój prowizoryczny prefiks, który potem będzie w konfiguracji. Teraz jest to `funnyguilds_`.

**Comment by SlimaKCoder** [comment]
@TheMolkaPL 
Ok, ja zwijam na dziś :)

**Comment by TheMolkaPL** [comment]
Pozwoliłem sobie dodać mały spis treści z linkami [w pierwszym poście](https://github.com/Wruczek/FunnyGuilds-Reloaded/issues/2#issue-111180504), które tutaj się przewijały, aby ewentualnie nie szukać. ;)

**Comment by NotJustPizza** [comment]
@TheMolkaPL 

Ok, to uzupełenię dependency :P

**Comment by TheMolkaPL** [comment]
@SlimaKCoder

Z tego

``` sql
create table `funnyguilds_guilds_relations` (
    `applicant_id` int not null, #Klucz obcy i część klucza podstawowego
    `receiver_id` int not null, #Klucz obcy i część klucza podstawowego
    `relation` bool, # 0 = rival, 1 = friend
    `assigned` datetime not null,
    `expires` datetime null,
    primary key (`applicant_id`, `receiver_id`)
 );
```

nie można zrobić tak?

``` sql
create table `funnyguilds_guilds_relations` (
    `applicant_id` int not null primary key, #Klucz obcy i część klucza podstawowego
    `receiver_id` int not null primary key, #Klucz obcy i część klucza podstawowego
    `relation` bool, # 0 = rival, 1 = friend
    `assigned` datetime not null,
    `expires` datetime null
 );
```

https://gist.github.com/SlimaKCoder/746e89ebdf2b3b9f3e21#file-databasemodel-sql-L74-#file-databasemodel-sql-L81

---

Tak poza tym `relation` proponowałbym zapisywać w `SMALLINT` lub `TINYINT`, bo może kiedyś dojdzie ich więcej. Baza powinna zostać napisana maksymalnie przyszłościowo.

**Comment by NotJustPizza** [comment]
@TheMolkaPL 
Sprawdź po prostu. Jak drugi raz użyjesz stałej "PRIMARY KEY" to wywali błąd, że już go zdefiniowano. Dlatego tworzysz klucz podstawowy na końcu z dwóch tabel jednocześnie.

@TheMolkaPL 
Relacja jest już zapisana w TINYINT (MySQL zapisuje BOOL jako TINYINT(1)). Nie ma sensu tego zmieniać, bo powiększenie rozmiaru zmiennej z rodziny INT nie stanowi problemu, a rezerwowanie niepotrzebnie miejsca jest nieekonomiczne. 

P.S. Ewentualnie można by zastąpić BOOL typem ENUM.

**Comment by TheMolkaPL** [comment]
@SlimaKCoder Przydałaby się jeszcze jakaś tabela ustawień typu klucz i wartość.
Można wtedy kontrolować ustawienia z ewentualnego panelu www ;)

**Comment by NotJustPizza** [comment]
@TheMolkaPL 

Wtedy ustawienia musiały by być w MySQL. Myślę, że lepiej zostawić je w pliku jak są.

**Comment by NotJustPizza** [comment]
Chyba napiszę dziś jakiś program PHP5 do wypchania bazy danych... ciężko mi pracować na pustej.

**Comment by TheMolkaPL** [comment]
#3 - polecam przejrzeć.

**Comment by NotJustPizza** [comment]
Powinniśmy zacząć dzielić prace na poszczególne issues, nie może być wszystko w jednym temacie.

**Comment by NotJustPizza** [comment]
Zapraszam do dyskusji: [#1](https://github.com/SlimaKCoder/projectQ-Reloaded/issues/1) [#2](https://github.com/SlimaKCoder/projectQ-Reloaded/issues/2) [#3](https://github.com/SlimaKCoder/projectQ-Reloaded/issues/3)

**Comment by Wruczek** [comment]
> @SlimaKCoder 
> Powinniśmy zacząć dzielić prace na poszczególne issues, nie może być wszystko w jednym temacie.

@all
By nie robić bałaganu:
#5 Ogólna dyskusja na temat wtyczki
#4 Dyskusja na temat wtyczki - bazy danych 
#6 Dyskusja na temat strony WWW (ranking)
