### ISSUE TITLE
Jak mam to pobrać?

### ISSUE THREAD

**Issue by Kubus6969** [Wruczek/FunnyGuilds-Reloaded#9]
Jak to mam pobrać? Jak to pobiore to będzie sourcecode, a i czy to napewno działa na 1.8.8?

**Comment by TheMolkaPL** [comment]
Obecnie pobieranie nie jest dostępne, aczkolwiek możesz to dla siebie skompilować.

**Comment by Kubus6969** [comment]
A mógłbyś za mnie skompilować?
Bo nie znam się na eclipsie, i wogóle.

**Comment by Wruczek** [comment]
Skompilowana wersja `.jar` będzie dostępna w [releases](https://github.com/Wruczek/FunnyGuilds-Reloaded/releases) gdy tylko zakończymy pracę nad pierwszą wersją.

**Comment by Kubus6969** [comment]
A jeśli można wiedzieć to kiedy będzie na 1.8? :+1:

**Comment by Kubus6969** [comment]
I czy jak będzie na tym 1.8+ to będzie działała tablista? ;________;

**Comment by Wruczek** [comment]
Nie jestem w stanie powiedzieć, kiedy wypuścimy FunnyGuilds-Reloaded 1.0.
Możesz kliknąć na przycisk "Watch" na górze strony, zostaniesz poinformowany gdy wyjdzie pierwsza wersja.
Oczywiście, tablista będzie działać.

**Comment by NotJustPizza** [comment]
@Wruczek 
Bez pracy nie ma kołaczy ;)

**Comment by TheMolkaPL** [comment]
@Wruczek a co w ogóle zmienia ta wersja 1.7, którą wydałeś?

**Comment by Wruczek** [comment]
Nic, jest to ostatnia wersja Dzikoyska.
Pomyślałem, że warto dodać plik jak i krótki opis do ostatniej wersji na 1.7, jeśli ktoś by tego tutaj szukał.
